In [5]:
import soup
import pandas as pd

In [17]:
time_casa, tecnico_casa, gols_casa, onze_casa, banco_casa, subs_dict_casa = soup.time_casa, soup.tecnico_casa, soup.gols_casa, soup.onze_casa, soup.banco_casa, soup.subs_dict_casa

time_fora, tecnico_fora, gols_fora, onze_fora, banco_fora, subs_dict_fora = soup.time_fora, soup.tecnico_fora, soup.gols_fora, soup.onze_fora, soup.banco_fora, soup.subs_dict_fora

sub1_casa, sub2_casa, sub3_casa, sub4_casa, sub5_casa, sub1_casa_tempo, sub2_casa_tempo, sub3_casa_tempo, sub4_casa_tempo, sub5_casa_tempo = soup.sub1_casa, soup.sub2_casa, soup.sub3_casa, soup.sub4_casa, soup.sub5_casa, soup.sub1_casa_tempo, soup.sub2_casa_tempo, soup.sub3_casa_tempo, soup.sub4_casa_tempo, soup.sub5_casa_tempo

sub1_fora, sub2_fora, sub3_fora, sub4_fora, sub5_fora, sub1_fora_tempo, sub2_fora_tempo, sub3_fora_tempo, sub4_fora_tempo, sub5_fora_tempo = soup.sub1_fora, soup.sub2_fora, soup.sub3_fora, soup.sub4_fora, soup.sub5_fora, soup.sub1_fora_tempo, soup.sub2_fora_tempo, soup.sub3_fora_tempo, soup.sub4_fora_tempo, soup.sub5_fora_tempo

dcts = [time_casa, tecnico_casa, time_fora, tecnico_fora, gols_casa, gols_fora, onze_casa, onze_fora, banco_casa, banco_fora, sub1_casa, sub2_casa, sub3_casa, sub4_casa, sub5_casa, sub1_casa_tempo, sub2_casa_tempo, sub3_casa_tempo, sub4_casa_tempo, sub5_casa_tempo, sub1_fora, sub2_fora, sub3_fora, sub4_fora, sub5_fora, sub1_fora_tempo, sub2_fora_tempo, sub3_fora_tempo, sub4_fora_tempo, sub5_fora_tempo]

dfs = pd.DataFrame([[time_casa.values(), tecnico_casa.values(), time_fora.values(), tecnico_fora.values(), gols_casa.values(), gols_fora.values(), 
                   onze_casa.values(), onze_fora.values(), banco_casa.values(), banco_fora.values(),
                   sub1_casa.values(), sub1_casa_tempo, sub2_casa.values(), sub2_casa_tempo, sub3_casa.values(), sub3_casa_tempo,
                   sub4_casa.values(), sub4_casa_tempo, sub5_casa.values(), sub5_casa_tempo,
                   sub1_fora.values(), sub1_fora_tempo, sub2_fora.values(), sub2_fora_tempo, 
                   sub3_fora.values(), sub3_fora_tempo, sub4_fora.values(), sub4_fora_tempo,
                   sub5_fora.values(), sub5_fora_tempo]])


cols = {'columns': {0: 'time_casa', 1: 'tecnico_casa', 2: 'time_fora', 3: 'tecnico_fora', 4: 'gols_casa', 5: 'gols_fora', 
                    6: '11_casa', 7: '11_fora', 8: 'banco_casa', 9: 'banco_fora', 10: 'sub1_casa',
                    11: 'sub1_casa_tempo', 12: 'sub2_casa', 13:'sub2_casa_tempo', 14: 'sub3_casa', 15:'sub3_casa_tempo', 16: 'sub4_casa',
                    17: 'sub4_casa_tempo', 18: 'sub5_casa', 19: 'sub5_casa_tempo',
                    20: 'sub1_fora', 21: 'sub1_fora_tempo', 22: 'sub2_fora', 23:'sub2_fora_tempo', 24: 'sub3_fora',
                    25:'sub3_fora_tempo', 26: 'sub4_fora', 27: 'sub4_fora_tempo', 28: 'sub5_fora', 29: 'sub5_fora_tempo'}}

dfs.reset_index(drop=True).rename(**cols)

# -------------------------------------------- 2

dfs2 = pd.DataFrame([[time_casa.values(), tecnico_casa.values(), time_fora.values(), tecnico_fora.values(), gols_casa.values(), gols_fora.values(), 
                   onze_casa.values(), onze_fora.values(), banco_casa.values(), banco_fora.values(),
                   sub1_casa.values(), sub1_casa_tempo, sub2_casa.values(), sub2_casa_tempo, sub3_casa.values(), sub3_casa_tempo,
                   sub4_casa.values(), sub4_casa_tempo, sub5_casa.values(), sub5_casa_tempo,
                   sub1_fora.values(), sub1_fora_tempo, sub2_fora.values(), sub2_fora_tempo, 
                   sub3_fora.values(), sub3_fora_tempo, sub4_fora.values(), sub4_fora_tempo,
                   sub5_fora.values(), sub5_fora_tempo]])


dfs2.reset_index(drop=True).rename(**cols)

dfs_final = pd.concat([dfs, dfs2], ignore_index=True, sort=False)
dfs_final

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,(Cuiabá),(Alberto Valentim),(Juventude),(Marquinhos Santos),(2),(2),"([Walter, Lucas Ramon, Marllon Borges, Anderso...","([Marcelo Carné, Michel, Vitor Mendes, Rafael ...","([João Carlos, João Lucas, Paulão, José Walber...","([William, Cleberson, Paulo Henrique, Elton, M...",...,"((Chico, Marcos Vinicios))",75,"((Michel, Paulo Henrique))",75,"((Matheus Peixoto, Fernando Pacheco Rivas))",88,"((Capixaba, Elton))",89,"((Alyson, Eltinho))",89
1,(Cuiabá),(Alberto Valentim),(Juventude),(Marquinhos Santos),(2),(2),"([Walter, Lucas Ramon, Marllon Borges, Anderso...","([Marcelo Carné, Michel, Vitor Mendes, Rafael ...","([João Carlos, João Lucas, Paulão, José Walber...","([William, Cleberson, Paulo Henrique, Elton, M...",...,"((Chico, Marcos Vinicios))",75,"((Michel, Paulo Henrique))",75,"((Matheus Peixoto, Fernando Pacheco Rivas))",88,"((Capixaba, Elton))",89,"((Alyson, Eltinho))",89